baseURL: https://justinas.eu/
languageCode: en-us
title: Justinas Pošiūnas | software development x engineering management
theme: posiunas

caches:
  images:
    dir: :cacheDir/images

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    meta:
        description: My virtual personal presence starts there!
    title: Justinas Pošiūnas
    subtitle: software development & engineering management
    links:
        - name: LinkedIn
          ico: fa-linkedin
          url: https://www.linkedin.com/in/posiunas

        - name: Goodreads
          ico: fa-goodreads
          url: https://www.goodreads.com/posiunas

        - name: GitHub
          ico: fa-github
          url: https://github.com/posiunas

        - name: Spotify
          ico: fa-spotify
          url: https://open.spotify.com/user/1176777925

        - name: X
          ico: fa-x-twitter
          url: https://x.com/nkwaerd

        - name: Messenger
          ico: fa-facebook-messenger
          url: https://m.me/nkwaerd
