baseURL: https://justinas.eu/
languageCode: en-us
title: Justinas Pošiūnas | software development x personal business
theme: posiunas

params:
    meta:
        description: My virtual personal presence starts there!
    title: Justinas Pošiūnas
    subtitle: software development personal business
    links:
        - name: LinkedIn
          ico: fa-linkedin
          url: https://www.linkedin.com/in/posiunas/

        - name: Goodreads
          ico: fa-goodreads
          url: https://www.goodreads.com/user/show/62544630-justinas

        - name: Instagram
          ico: fa-instagram
          url: https://instgram.com/nkwaerd

        - name: GitHub
          ico: fa-github
          url: https://github.com/posiunas

        - name: Spotify
          ico: fa-spotify
          url: https://open.spotify.com/user/1176777925

        - name: Twitter
          ico: fa-twitter
          url: https://twitter.com/nkwaerd

        - name: Messenger
          ico: fa-facebook-messenger
          url: https://m.me/nkwaerd